controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller_right:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_trajectory_controller_left:
      type: joint_trajectory_controller/JointTrajectoryController

    base_position_controller:
      type: position_controllers/JointGroupPositionController

    base_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    base_effort_controller:
      type: effort_controllers/JointGroupEffortController

joint_trajectory_controller_left:
  ros__parameters:
    joints:
      - kinova_left_joint_1
      - kinova_left_joint_2
      - kinova_left_joint_3
      - kinova_left_joint_4
      - kinova_left_joint_5
      - kinova_left_joint_6
      - kinova_left_joint_7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.0
      goal_time: 0.0


joint_trajectory_controller_right:
  ros__parameters:
    joints:
      - kinova_right_joint_1
      - kinova_right_joint_2
      - kinova_right_joint_3
      - kinova_right_joint_4
      - kinova_right_joint_5
      - kinova_right_joint_6
      - kinova_right_joint_7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.0
      goal_time: 0.0

base_position_controller:
  ros__parameters:
    joints:
      - kelo_drive_front_left_hub_left_joint
      - kelo_drive_front_left_hub_right_joint
      - kelo_drive_front_right_hub_left_joint
      - kelo_drive_front_right_hub_right_joint
      - kelo_drive_rear_right_hub_left_joint
      - kelo_drive_rear_right_hub_right_joint
      - kelo_drive_rear_left_hub_left_joint
      - kelo_drive_rear_left_hub_right_joint

base_velocity_controller:
  ros__parameters:
    joints:
      - kelo_drive_front_left_hub_left_joint
      - kelo_drive_front_left_hub_right_joint
      - kelo_drive_front_right_hub_left_joint
      - kelo_drive_front_right_hub_right_joint
      - kelo_drive_rear_right_hub_left_joint
      - kelo_drive_rear_right_hub_right_joint
      - kelo_drive_rear_left_hub_left_joint
      - kelo_drive_rear_left_hub_right_joint

base_effort_controller:
  ros__parameters:
    joints:
      - kelo_drive_front_left_hub_left_joint
      - kelo_drive_front_left_hub_right_joint
      - kelo_drive_front_right_hub_left_joint
      - kelo_drive_front_right_hub_right_joint
      - kelo_drive_rear_right_hub_left_joint
      - kelo_drive_rear_right_hub_right_joint
      - kelo_drive_rear_left_hub_left_joint
      - kelo_drive_rear_left_hub_right_joint
